// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	datapath: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("datapath", { path })),
	prompt: (request: LlmPromptRequest_Deserialize) => typedError<null, AppError>(__TAURI_INVOKE("prompt", { request })),
	listModels: () => typedError<{ [key in string]: ModelConfig_Serialize }, AppError>(__TAURI_INVOKE("list_models")),
	saveModels: (models: { [key in string]: ModelConfig_Deserialize }) => typedError<null, AppError>(__TAURI_INVOKE("save_models", { models })),
	pingHosts: () => typedError<UnreachableHost[], AppError>(__TAURI_INVOKE("ping_hosts")),
	pingHost: (request: PingHostRequest_Deserialize) => typedError<string | null, AppError>(__TAURI_INVOKE("ping_host", { request })),
	sessionList: () => typedError<SessionMeta_Serialize[], AppError>(__TAURI_INVOKE("session_list")),
	sessionCreate: (req: SessionCreateRequest_Deserialize) => typedError<SessionCreateResult, AppError>(__TAURI_INVOKE("session_create", { req })),
	sessionDelete: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("session_delete", { id })),
	sessionLoad: (id: string) => typedError<SessionLoadResult_Serialize, AppError>(__TAURI_INVOKE("session_load", { id })),
	sessionSaveMeta: (meta: SessionMeta_Deserialize) => typedError<null, AppError>(__TAURI_INVOKE("session_save_meta", { meta })),
	sessionUpsertPage: (req: SessionUpsertPageRequest_Deserialize) => typedError<null, AppError>(__TAURI_INVOKE("session_upsert_page", { req })),
	sessionTruncatePages: (sessionId: string, fromIndex: number) => typedError<null, AppError>(__TAURI_INVOKE("session_truncate_pages", { sessionId, fromIndex })),
	sessionGetHeadSnapshot: (sessionId: string) => typedError<{
	version: number,
	id: string,
	sessionId: string,
	pageIndex: number,
	data: any,
} | null, AppError>(__TAURI_INVOKE("session_get_head_snapshot", { sessionId })),
	sessionSaveHeadSnapshot: (sessionId: string, snapshot: Snapshot) => typedError<null, AppError>(__TAURI_INVOKE("session_save_head_snapshot", { sessionId, snapshot })),
	sessionDeleteHeadSnapshot: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("session_delete_head_snapshot", { sessionId })),
	sessionFindSnapshotBefore: (sessionId: string, pageIndex: number) => typedError<{
	version: number,
	id: string,
	sessionId: string,
	pageIndex: number,
	data: any,
} | null, AppError>(__TAURI_INVOKE("session_find_snapshot_before", { sessionId, pageIndex })),
	sessionSaveCheckpoint: (sessionId: string, snapshot: Snapshot) => typedError<null, AppError>(__TAURI_INVOKE("session_save_checkpoint", { sessionId, snapshot })),
	sessionDeleteCheckpointsFrom: (sessionId: string, fromPageIndex: number) => typedError<null, AppError>(__TAURI_INVOKE("session_delete_checkpoints_from", { sessionId, fromPageIndex })),
	profileList: () => typedError<ProfileListResult, AppError>(__TAURI_INVOKE("profile_list")),
	profileCreate: (id: string, name: string, fields: { [key in string]: string }, createdAt: string) => typedError<null, AppError>(__TAURI_INVOKE("profile_create", { id, name, fields, createdAt })),
	profileUpdate: (id: string, name: string, fields: { [key in string]: string }, updatedAt: string) => typedError<null, AppError>(__TAURI_INVOKE("profile_update", { id, name, fields, updatedAt })),
	profileDelete: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("profile_delete", { id })),
	profileSetActive: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("profile_set_active", { id })),
	storyGet: (id: string) => typedError<{
	version: number,
	id: string,
	title: string,
	description?: string | null,
	config: any,
	created_at: string,
	updated_at: string,
} | null, AppError>(__TAURI_INVOKE("story_get", { id })),
	storySave: (story: StoryEntry_Deserialize) => typedError<null, AppError>(__TAURI_INVOKE("story_save", { story })),
	loreQuery: (storyId: string, query: string) => typedError<LoreQueryResult_Serialize[], AppError>(__TAURI_INVOKE("lore_query", { storyId, query })),
};

/* Types */
export type AppError = { kind: "io"; detail: string } | { kind: "not_found"; detail: string } | { kind: "validation"; detail: string } | { kind: "llm"; detail: string } | { kind: "path"; detail: string } | { kind: "parse"; detail: string } | { kind: "internal"; detail: string };

export type FunctionCall = {
	name: string,
	arguments: string,
};

export type LlmMessage = LlmMessage_Serialize | LlmMessage_Deserialize;

export type LlmMessage_Deserialize = {
	author: string,
	content: string,
	tool_call_id?: string | null,
	tool_calls?: ToolCall[] | null,
};

export type LlmMessage_Serialize = {
	author: string,
	content: string,
	tool_call_id?: string | null,
	tool_calls?: ToolCall[] | null,
};

export type LlmPromptRequest = LlmPromptRequest_Serialize | LlmPromptRequest_Deserialize;

export type LlmPromptRequest_Deserialize = {
	model: string,
	messages: LlmMessage_Deserialize[],
	persona?: string | null,
	context?: any,
	request_id?: string | null,
	tools?: LlmTool_Deserialize[] | null,
};

export type LlmPromptRequest_Serialize = {
	model: string,
	messages: LlmMessage_Serialize[],
	persona?: string | null,
	context?: any,
	request_id?: string | null,
	tools?: LlmTool_Serialize[] | null,
};

export type LlmTool = LlmTool_Serialize | LlmTool_Deserialize;

export type LlmTool_Deserialize = {
	name: string,
	description?: string | null,
	parameters?: any,
};

export type LlmTool_Serialize = {
	name: string,
	description?: string | null,
	parameters?: any,
};

export type LoreQueryResult = LoreQueryResult_Serialize | LoreQueryResult_Deserialize;

export type LoreQueryResult_Deserialize = {
	id: string,
	title: string,
	content: string,
	tags: string[] | null,
};

export type LoreQueryResult_Serialize = {
	id: string,
	title: string,
	content: string,
	tags?: string[] | null,
};

export type ModelConfig = ModelConfig_Serialize | ModelConfig_Deserialize;

export type ModelConfig_Deserialize = {
	base_url: string,
	model_id: string,
	api_key: string | null,
};

export type ModelConfig_Serialize = {
	base_url: string,
	model_id: string,
	api_key?: string | null,
};

export type PageEntry = PageEntry_Serialize | PageEntry_Deserialize;

export type PageEntry_Deserialize = {
	id: string,
	sessionId: string,
	system: string | null,
	prompt: string | null,
	response: string | null,
	toolCalls: string | null,
};

export type PageEntry_Serialize = {
	id: string,
	sessionId: string,
	system?: string | null,
	prompt?: string | null,
	response?: string | null,
	toolCalls?: string | null,
};

export type PingHostRequest = PingHostRequest_Serialize | PingHostRequest_Deserialize;

export type PingHostRequest_Deserialize = {
	url: string,
	api_key?: string | null,
};

export type PingHostRequest_Serialize = {
	url: string,
	api_key?: string | null,
};

export type Profile = {
	id: string,
	name: string,
	fields: { [key in string]: string },
	created_at: string,
	updated_at: string,
};

export type ProfileListResult = {
	profiles: Profile[],
	active_id: string | null,
};

export type SessionCreateRequest = SessionCreateRequest_Serialize | SessionCreateRequest_Deserialize;

export type SessionCreateRequest_Deserialize = {
	story_id: string | null,
	title: string,
};

export type SessionCreateRequest_Serialize = {
	story_id?: string | null,
	title: string,
};

export type SessionCreateResult = {
	session_id: string,
	snapshot_id: string,
};

export type SessionLoadResult = SessionLoadResult_Serialize | SessionLoadResult_Deserialize;

export type SessionLoadResult_Deserialize = {
	meta: SessionMeta_Deserialize,
	pages: PageEntry_Deserialize[],
};

export type SessionLoadResult_Serialize = {
	meta: SessionMeta_Serialize,
	pages: PageEntry_Serialize[],
};

export type SessionMeta = SessionMeta_Serialize | SessionMeta_Deserialize;

export type SessionMeta_Deserialize = {
	version: number,
	id: string,
	storyId: string | null,
	title: string,
	description: string | null,
	createdAt: string,
	updatedAt: string,
};

export type SessionMeta_Serialize = {
	version: number,
	id: string,
	storyId?: string | null,
	title: string,
	description?: string | null,
	createdAt: string,
	updatedAt: string,
};

export type SessionUpsertPageRequest = SessionUpsertPageRequest_Serialize | SessionUpsertPageRequest_Deserialize;

export type SessionUpsertPageRequest_Deserialize = {
	session_id: string,
	page_index: number | null,
	page: PageEntry_Deserialize,
};

export type SessionUpsertPageRequest_Serialize = {
	session_id: string,
	page_index?: number | null,
	page: PageEntry_Serialize,
};

export type Snapshot = {
	version: number,
	id: string,
	sessionId: string,
	pageIndex: number,
	data: any,
};

export type StoryEntry = StoryEntry_Serialize | StoryEntry_Deserialize;

export type StoryEntry_Deserialize = {
	version: number,
	id: string,
	title: string,
	description: string | null,
	config: any,
	created_at: string,
	updated_at: string,
};

export type StoryEntry_Serialize = {
	version: number,
	id: string,
	title: string,
	description?: string | null,
	config: any,
	created_at: string,
	updated_at: string,
};

export type ToolCall = {
	id: string,
	type: string,
	function: FunctionCall,
};

export type UnreachableHost = {
	url: string,
	error: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

